repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.11
