name: Quality and Tests

on:
  push:
    branches: [main]
  merge_group:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: |
        python -m pip install pipenv
        pipenv install --dev
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: --show-diff-on-failure

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: |
        python -m pip install pipenv
        pipenv install --dev
        pipenv run python -m pip install -e .
        pipenv run pytest